package main

// Sizes measured in the pinned signed installer, after upstream signing/packaging.
// Its ASAR unpacked-size metadata predates 43 upstream native-signature/package changes.
var packagedUnpackedSizes = map[string]int64{
	"cli/bin/native/win32-x64/job-object.node":                                                 298544,
	"cli/node_modules/@lydell/node-pty-win32-x64/prebuilds/win32-x64/conpty.node":              302128,
	"cli/node_modules/@lydell/node-pty-win32-x64/prebuilds/win32-x64/conpty/OpenConsole.exe":   1084096,
	"cli/node_modules/@lydell/node-pty-win32-x64/prebuilds/win32-x64/conpty_console_list.node": 145448,
	"cli/node_modules/@lydell/node-pty/package.json":                                           897,
	"cli/node_modules/koffi/build/koffi/win32_x64/koffi.node":                                  1614384,
	"cli/node_modules/koffi/package.json":                                                      981,
	"cli/node_modules/koffi/src/cnoke/package.json":                                            506,
	"cli/vendor/genie-trash/win32-x64.exe":                                                     2670360,
	"cli/vendor/ripgrep/x64-win32/rg.exe":                                                      5418544,
	"cli/vendor/ripgrep/x64-win32/ripgrep.node":                                                6976560,
	"cli/vendor/sandbox/5.6.10/betterleaks.exe":                                                22850088,
	"cli/vendor/sandbox/5.6.10/sandbox-center.exe":                                             8020008,
	"cli/vendor/sandbox/5.6.10/sandbox-cli-gc.exe":                                             652840,
	"cli/vendor/sandbox/5.6.10/sandbox-cli.exe":                                                2146864,
	"cli/vendor/sandbox/5.6.10/sandbox_ffi.dll":                                                1998896,
	"cli/vendor/sandbox/5.6.10/tsbx.dll":                                                       709168,
	"cli/vendor/sandbox/5.6.10/tsbx_sdk.dll":                                                   527408,
	"native/perf-metrics/build/Release/perf_metrics.node":                                      174640,
	"native/turing-sdk/build/Release/turing_sdk.node":                                          162344,
	"native/wechat-copydata-decoder/build/Release/wechat_copydata_decoder.node":                122928,
	"node_modules/@lydell/node-pty-win32-arm64/prebuilds/win32-arm64/conpty/OpenConsole.exe":   1121384,
	"node_modules/@lydell/node-pty-win32-x64/prebuilds/win32-x64/conpty.node":                  302128,
	"node_modules/@lydell/node-pty-win32-x64/prebuilds/win32-x64/conpty/OpenConsole.exe":       1073296,
	"node_modules/@lydell/node-pty-win32-x64/prebuilds/win32-x64/conpty_console_list.node":     145448,
	"node_modules/@tencent/qimei-node/build/Release/qimei.node":                                116784,
	"node_modules/@tencent/tencent-docs-ai-engine/bin/win32-x64/editor_sdk.exe":                209505392,
	"node_modules/better-sqlite3/build/Release/better_sqlite3.node":                            1912360,
	"node_modules/better-sqlite3/package.json":                                                 1427,
	"node_modules/koffi/build/koffi/win32_x64/koffi.node":                                      1614384,
	"node_modules/koffi/package.json":                                                          981,
	"node_modules/koffi/src/cnoke/package.json":                                                506,
	"node_modules/node-pty/build/Release/conpty/OpenConsole.exe":                               1159272,
	"node_modules/node-pty/prebuilds/win32-arm64/conpty/OpenConsole.exe":                       1204848,
	"node_modules/node-pty/prebuilds/win32-arm64/winpty-agent.exe":                             297512,
	"node_modules/node-pty/prebuilds/win32-x64/conpty.node":                                    323112,
	"node_modules/node-pty/prebuilds/win32-x64/conpty/OpenConsole.exe":                         1159272,
	"node_modules/node-pty/prebuilds/win32-x64/conpty_console_list.node":                       145456,
	"node_modules/node-pty/prebuilds/win32-x64/pty.node":                                       313896,
	"node_modules/node-pty/prebuilds/win32-x64/winpty-agent.exe":                               318512,
	"node_modules/node-pty/third_party/conpty/1.23.251008001/win10-arm64/OpenConsole.exe":      1204848,
	"node_modules/node-pty/third_party/conpty/1.23.251008001/win10-x64/OpenConsole.exe":        1159272,
	"resources/plugins/workbuddy-builtin/mcps/agently-cli/bin/agently-cli.exe":                 9305136,
}
